test:
  sessions:
    default:
      database: contraband_test
      hosts:
        - localhost:27017
      options:
        allow_dynamic_fields: false
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0